export interface HeaderOptions {
  source: string;
  mode: "generated" | "vendored";
}

/**
 * Render the HTML-comment header for a generated or vendored target file.
 * Must match the spec's exact text.
 */
export function renderHeader(opts: HeaderOptions): string {
  if (opts.mode === "generated") {
    return [
      "<!--",
      "Generated by agent-library.",
      `Source: ${opts.source}`,
      "Mode: generated",
      "Do not edit this file directly. Edit the source in ~/.agent-library or the project .agent-library source.",
      "-->",
    ].join("\n");
  }

  return [
    "<!--",
    "Vendored from agent-library.",
    `Source: ${opts.source}`,
    "Mode: vendored",
    "This project owns this copy. Local edits are allowed.",
    "The sync tool will update it only if it is unchanged from the last recorded source.",
    "-->",
  ].join("\n");
}

/** The marker string used to identify generated files — must appear in the header. */
export const GENERATED_MARKER = "Generated by agent-library.";
/** The marker string used to identify vendored files. */
export const VENDORED_MARKER = "Vendored from agent-library.";
