import { describe, it, expect, beforeEach, afterEach } from "bun:test";
import { resolve, join } from "node:path";
import { cpSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";

const HOME = resolve("tests/fixtures/home-min");
const FIXTURE = resolve("tests/fixtures/projects/p2-mixed");

// Mutable — assigned fresh in beforeEach so parallel file-level runs don't share state.
let PROJECT: string;

function run(args: string[]): { stdout: string; stderr: string; code: number } {
  const result = Bun.spawnSync(["./bin/agent-library", ...args], {
    env: { ...process.env, HOME_AGENT_LIBRARY: HOME },
  });
  return {
    stdout: result.stdout.toString(),
    stderr: result.stderr.toString(),
    code: result.exitCode ?? 1,
  };
}

describe("sync generated mixed (commands, agents, dual targets)", () => {
  beforeEach(() => {
    PROJECT = mkdtempSync(join(tmpdir(), "al-test-mixed-"));
    cpSync(FIXTURE, PROJECT, { recursive: true });
  });
  afterEach(() => {
    rmSync(PROJECT, { recursive: true, force: true });
  });

  it("writes all 6 target files with generated headers", async () => {
    const r = run(["sync", PROJECT]);
    expect(r.code).toBe(0);

    const expectedFiles = [
      // skills × 2 targets
      join(PROJECT, ".agents", "skills", "writing-plans", "SKILL.md"),
      join(PROJECT, ".claude", "skills", "writing-plans", "SKILL.md"),
      // commands × 2 targets
      join(PROJECT, ".agents", "commands", "review-pr.md"),
      join(PROJECT, ".claude", "commands", "review-pr.md"),
      // agents × 2 targets
      join(PROJECT, ".agents", "agents", "security-reviewer.md"),
      join(PROJECT, ".claude", "agents", "security-reviewer.md"),
    ];

    for (const f of expectedFiles) {
      expect(await Bun.file(f).exists()).toBe(true);
      const content = await Bun.file(f).text();
      expect(content).toContain("Generated by agent-library.");
      if (f.endsWith("SKILL.md")) {
        expect(content.startsWith("---\n")).toBe(true);
      }
    }
  });

  it("skill SKILL.md contains original body", async () => {
    run(["sync", PROJECT]);
    const content = await Bun.file(
      join(PROJECT, ".claude", "skills", "writing-plans", "SKILL.md"),
    ).text();
    expect(content).toContain("Source: global/skills/writing-plans");
    expect(content).toContain("Mode: generated");
  });

  it("command file contains original body", async () => {
    run(["sync", PROJECT]);
    const content = await Bun.file(
      join(PROJECT, ".claude", "commands", "review-pr.md"),
    ).text();
    expect(content).toContain("Source: global/commands/review-pr");
    expect(content).toContain("Review PR Command");
  });

  it("agent file contains original body", async () => {
    run(["sync", PROJECT]);
    const content = await Bun.file(
      join(PROJECT, ".agents", "agents", "security-reviewer.md"),
    ).text();
    expect(content).toContain("Source: global/agents/security-reviewer");
    expect(content).toContain("Security Reviewer Agent");
  });
});
