import { describe, it, expect, beforeEach, afterEach } from "bun:test";
import { resolve, join } from "node:path";
import { cpSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { readLockfile } from "../../src/lockfile/read.ts";

const HOME = resolve("tests/fixtures/home-min");
const FIXTURE = resolve("tests/fixtures/projects/p7-bundle");

let PROJECT: string;

function run(args: string[]): { stdout: string; stderr: string; code: number } {
  const result = Bun.spawnSync(["./bin/agent-library", ...args], {
    env: { ...process.env, HOME_AGENT_LIBRARY: HOME },
  });
  return {
    stdout: result.stdout.toString(),
    stderr: result.stderr.toString(),
    code: result.exitCode ?? 1,
  };
}

describe("sync bundle expansion lockfile", () => {
  beforeEach(() => {
    PROJECT = mkdtempSync(join(tmpdir(), "al-test-bundle-"));
    cpSync(FIXTURE, PROJECT, { recursive: true });
  });
  afterEach(() => {
    rmSync(PROJECT, { recursive: true, force: true });
  });

  it("records original bundle includes and expanded artifact ids", async () => {
    const r = run(["sync", PROJECT]);
    expect(r.code).toBe(0);

    const lockfileResult = await readLockfile(join(PROJECT, ".agent-library.lock"));
    expect(lockfileResult.ok).toBe(true);
    if (!lockfileResult.ok) return;
    expect(lockfileResult.value).not.toBeNull();
    if (lockfileResult.value === null) return;
    expect(lockfileResult.value.include).toEqual(["global"]);
    expect(lockfileResult.value.artifacts.map((a) => a.id).sort()).toEqual([
      "global/agents/security-reviewer",
      "global/commands/review-pr",
      "global/skills/writing-plans",
    ]);
  });

  it("copies bundled skill files alongside SKILL.md", async () => {
    const r = run(["sync", PROJECT]);
    expect(r.code).toBe(0);

    // p7-bundle targets claude only, so check .claude
    const bundledTarget = join(
      PROJECT,
      ".claude",
      "skills",
      "writing-plans",
      "template.md",
    );
    expect(await Bun.file(bundledTarget).exists()).toBe(true);
  });

  it("bundled markdown file carries the generated ownership header", async () => {
    run(["sync", PROJECT]);

    const content = await Bun.file(
      join(PROJECT, ".claude", "skills", "writing-plans", "template.md"),
    ).text();
    expect(content).toContain("Generated by agent-library.");
    expect(content).toContain("Source: global/skills/writing-plans");
  });

  it("bundled file body is preserved in the target", async () => {
    run(["sync", PROJECT]);

    const content = await Bun.file(
      join(PROJECT, ".claude", "skills", "writing-plans", "template.md"),
    ).text();
    expect(content).toContain("bundled template file");
  });

  it("lockfile records bundled file as a distinct source entry in the skill artifact", async () => {
    run(["sync", PROJECT]);

    const lockfileResult = await readLockfile(join(PROJECT, ".agent-library.lock"));
    expect(lockfileResult.ok).toBe(true);
    if (!lockfileResult.ok) return;
    expect(lockfileResult.value).not.toBeNull();
    if (lockfileResult.value === null) return;

    const skill = lockfileResult.value.artifacts.find(
      (a) => a.id === "global/skills/writing-plans",
    );
    expect(skill).toBeDefined();
    const sources = skill!.files.map((f) => f.source).sort();
    expect(sources).toContain("global/skills/writing-plans/SKILL.md");
    expect(sources).toContain("global/skills/writing-plans/template.md");
  });
});
