import { describe, it, expect, beforeEach, afterEach } from "bun:test";
import { resolve, join } from "node:path";
import { rmSync } from "node:fs";

const HOME = resolve("tests/fixtures/home-min");
const PROJECT = resolve("tests/fixtures/projects/p6-local");

function run(args: string[]): { stdout: string; stderr: string; code: number } {
  const result = Bun.spawnSync(["./bin/agent-library", ...args], {
    env: { ...process.env, HOME_AGENT_LIBRARY: HOME },
  });
  return {
    stdout: result.stdout.toString(),
    stderr: result.stderr.toString(),
    code: result.exitCode ?? 1,
  };
}

function cleanTargets() {
  rmSync(join(PROJECT, ".claude"), { recursive: true, force: true });
  rmSync(join(PROJECT, ".agent-library.lock"), { force: true });
}

describe("sync project-local includes", () => {
  beforeEach(cleanTargets);
  afterEach(cleanTargets);

  it("resolves ./ includes from the project-local source root", async () => {
    const r = run(["sync", PROJECT]);
    expect(r.code).toBe(0);

    const localTarget = join(
      PROJECT,
      ".claude",
      "skills",
      "domain-review",
      "SKILL.md",
    );
    const globalTarget = join(
      PROJECT,
      ".claude",
      "skills",
      "writing-plans",
      "SKILL.md",
    );

    expect(await Bun.file(localTarget).exists()).toBe(true);
    expect(await Bun.file(globalTarget).exists()).toBe(true);

    const localContent = await Bun.file(localTarget).text();
    const globalContent = await Bun.file(globalTarget).text();

    expect(localContent).toContain("Generated by agent-library.");
    expect(localContent).toContain("Source: ./product/skills/domain-review");
    expect(localContent).toContain("# Domain Review");
    expect(globalContent).toContain("Generated by agent-library.");
    expect(globalContent).toContain("Source: global/skills/writing-plans");
  });
});
