import { describe, it, expect, beforeEach, afterEach } from "bun:test";
import { resolve, join } from "node:path";
import { rmSync } from "node:fs";

const HOME = resolve("tests/fixtures/home-min");
const PROJECT = resolve("tests/fixtures/projects/p1-skill-only");

function run(args: string[]): { stdout: string; stderr: string; code: number } {
  const result = Bun.spawnSync(["bun", "run", "src/cli.ts", ...args], {
    env: { ...process.env, HOME_AGENT_LIBRARY: HOME },
  });
  return {
    stdout: result.stdout.toString(),
    stderr: result.stderr.toString(),
    code: result.exitCode ?? 1,
  };
}

function cleanTargets() {
  rmSync(join(PROJECT, ".claude"), { recursive: true, force: true });
  rmSync(join(PROJECT, ".agent-library.lock"), { force: true });
}

describe("sync generated skill", () => {
  beforeEach(cleanTargets);
  afterEach(cleanTargets);

  it("writes SKILL.md with frontmatter before the generated header", async () => {
    const r = run(["sync", "--home", HOME, PROJECT]);
    expect(r.code).toBe(0);

    const target = join(
      PROJECT,
      ".claude",
      "skills",
      "react-useeffect",
      "SKILL.md",
    );
    expect(await Bun.file(target).exists()).toBe(true);

    const content = await Bun.file(target).text();
    expect(content.startsWith("---\n")).toBe(true);
    expect(content.indexOf("Generated by agent-library.")).toBeGreaterThan(
      content.indexOf("\n---\n"),
    );
    expect(content).toContain("Generated by agent-library.");
    expect(content).toContain("Source: frontend/skills/react-useeffect");
    expect(content).toContain("Mode: generated");
    // Original body is preserved
    expect(content).toContain("# React useEffect Skill");
  });

  it("exits 1 with a name mismatch error for bad-name skill", async () => {
    // Create a temp manifest including the bad-name skill
    const badManifestDir = resolve("tests/fixtures/projects/p1-bad-name-temp");
    await Bun.write(
      join(badManifestDir, ".agent-library.yml"),
      "version: 1\nmode: generated\ntarget: claude\ninclude:\n  - frontend/skills/bad-name\nsource:\n  type: github\n  repo: org/repo\n  ref: main\n",
    );

    try {
      const r = run(["sync", "--home", HOME, badManifestDir]);
      expect(r.code).toBe(1);
      expect(r.stderr).toMatch(/name.*does not match/i);
    } finally {
      rmSync(badManifestDir, { recursive: true, force: true });
    }
  });
});
