import { describe, it, expect } from "bun:test";
import { renderHeader } from "../../src/sync/header.ts";

describe("renderHeader", () => {
  it("produces the canonical generated marker with source path", () => {
    const h = renderHeader({
      source: "frontend/skills/react-useeffect",
      mode: "generated",
    });
    expect(h).toContain("Generated by agent-library");
    expect(h).toContain("Source: frontend/skills/react-useeffect");
    expect(h).toContain("Mode: generated");
    expect(h.startsWith("<!--")).toBe(true);
    expect(h.trimEnd().endsWith("-->")).toBe(true);
  });

  it("produces the canonical vendored marker with source path", () => {
    const h = renderHeader({
      source: "frontend/skills/react-useeffect",
      mode: "vendored",
    });
    expect(h).toContain("Vendored from agent-library");
    expect(h).toContain("Source: frontend/skills/react-useeffect");
    expect(h).toContain("Mode: vendored");
    expect(h.startsWith("<!--")).toBe(true);
    expect(h.trimEnd().endsWith("-->")).toBe(true);
  });
});
